service: pepega-board-api

provider:
  name: aws
  runtime: nodejs16.x
  region: us-west-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Query"
            - "dynamodb:Scan"
          Resource:
            # will eventually replace this wildcard
            - "*"
            #- { "Fn::GetAtt": ["PepegaBoardTable", "Arn"] }

functions:
  register:
    handler: src/functions/auth.register
    events:
      - http:
          path: pepega-board-api/register
          method: post
  login:
    handler: src/functions/auth.login
    events:
      - http:
          path: pepega-board-api/login
          method: get

plugins:
  - serverless-plugin-typescript

resources:
  Resources:
    PepegaBoardTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: pepega-board
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: username-index
            KeySchema:
              - AttributeName: username
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 2
              WriteCapacityUnits: 2

